### PR TITLE
moved the blog to /blog path to make the CNAME stuff work

### PR DESCRIPTION
**Pull request by jamestwebber**
This was the easiest possible way to get that to resolve (I hope). And now we have space for a DS home page

### CODE REVIEW

**Comment by neevor** [comment]
So this worked for me locally, but doens't seem to be working on github now.

**Comment by neevor** [comment]
/blog.html does though.

**Comment by jamestwebber** [comment]
Well dang

**Comment by jamestwebber** [comment]
We both googled the same thing and probably both found https://github.com/jekyll/jekyll/issues/5023 or elsewhere

**Comment by neevor** [comment]
Oh that would have been really useful. I read through a bunch of Jekyll
documentation which took more time than doing a good google search.

**Pull request merged**
